#!/bin/bash
##ENVIRONMENT SETTINGS; CHANGE WITH CAUTION
#SBATCH --export=NONE                #Do not propagate environment
#SBATCH --get-user-env=L             #Replicate login environment

##NECESSARY JOB SPECIFICATIONS
#SBATCH --job-name=L2L-qua 
#SBATCH --time=24:00:00              
#SBATCH --ntasks=28                  
#SBATCH --mem=30G                  
#SBATCH --output=my_output     
#SBATCH --gres=gpu:1                 #Request 1 GPU per node can be 1 or 2
#SBATCH --partition=gpu              #Request the GPU partition/queue

##OPTIONAL JOB SPECIFICATIONS
#SBATCH --mail-type=ALL              #Send email on all job events
#SBATCH --mail-user=cyppsp@tamu.edu    #Send all emails to email_address 
#SBATCH --account=122797759557


#First Executable Line
source activate L2L
module load cuDNN/5.1-CUDA-8.0.44
python train.py --problem=quadratic --save_path=./quadratic
source deactivate
